### ISSUE TITLE
Suggestion/Feature Request: Animation chaining

### ISSUE THREAD

**Issue by davidseth** [Baste-RainGames/AnimationPlayer#3]
@Baste-RainGames Could you add Animation Chaining to your framework? Similar to https://github.com/prime31/ZestKit or DoTween http://dotween.demigiant.com/getstarted.php ?

I'm thinking something like:

`Play("SomeAnimation", <float Duration>).SetTransition(TransitionType.EaseIn).Play("AnotherAnimation");`

This would play SomeAnimation with a duration of Duration and then ease into AnotherAnimation.

And this could be extended with looping:

`Play("SomeAnimation", <float Duration>).SetTransition(TransitionType.EaseIn).Play("AnotherAnimation").SetLoops(2).SetLoopType(LoopType.PingPong);`

This would play SomeAnimation with a duration of Duration and then ease into AnotherAnimation with a total loop count of 2 with a PingPong behaviour.

**Comment by Baste-RainGames** [comment]
I have plans for adding the ability to queue up transitions. It would look something like:

animationPlayer.Play("SomeAnimation");
animationPlayer.PlayAfterSeconds(seconds, "SomeOtherAnimation");

PlayAfterSeconds will probably have a relative version (which takes input between 0 and 1 for how long into the animation it will automatically transition). The API will also probably mirror the API for Play, so if you want to specify the transition, you either give the name of one defined in the editor, or send a custom one as an argument.

I think the cleanest thing to do is that whenever Play is called, all queued transitions gets dropped. Otherwise you'll get into weird race condition situations.


I'll probably not have the API be chaining (ie. Play().Wait().Play()) unless I find it _really_ necessary. Chaining APIs often leads to a lot of complexity in the implementation for very little gain in readability. From your example - consider what SetTransition returns. It's got to be some kind of helper object thing that's probably hard to read. 



I don't want this to be a tweening engine, so the second example goes out. If you want that behaviour, I would suggest building it through pure playables and a tweening engine that supports generic callback based tweens for blending.

**Comment by davidseth** [comment]
Sounds really good. Thanks for your explanation.
