### ISSUE TITLE
Animation Events weird firing behavior

### ISSUE THREAD

**Issue by rgvox** [Baste-RainGames/AnimationPlayer#9]
Here is what my animation clips look like in Unity.  All of these events are baked into the clips themselves before being loaded into the AnimationPlayer:
Timeline below with events A() and D():
0               1               2               3               4               5               6               7
<---------------------A()--------------------------------D()------------------------------>

The events DO fire when I play the animation, however they fire like this
frame    | event firings
0             D() and A() simultaneously fire (backward order) immediately around the first frame of the animation.
1             --
2             A() normal/expected
3             --
4             --
5             D() normal/expected

I'm going to attempt to ignore the first 2 firings because I haven't figured out what is causing this yet.  If you can figure it out, let me know :)

**Comment by Baste-RainGames** [comment]
Hi!

I can't reproduce this. If I put in two events, they fire as expected. Could you post the stack trace of the events that fire at frame 0? 

I just did a look over the Animation Event system due to this issue, and while I didn't find the cause of the bug, I did clean up some strange handling of the special case of the default state having an animation event registered at time 0, which is the only thing I could see that could cause something to be off.

I also introduced two new settings for events that has been in my backlog - a toogleable requirement for the state to be active for the state to be fired, and a minimum weight required for the state to be fired (relevant during blending). The related cleanup might have fixed your bug - or caused new ones! Please tell me if either's the case.
